src/ace/managers/blit.c

Related to our discussion about C casting syntax. Some parentheses weren't necessary.

Simplified casting in blitter pointers

---

include/ace/macros.h
include/ace/managers/key.h
include/ace/managers/mouse.h
include/ace/utils/custom.h
src/ace/managers/key.c
src/ace/managers/mouse.c
src/ace/utils/custom.c

This pull requests closes pull request #13 and does some work for #24 . Also, it brings as closer to abandoning intuition.

Hardware keyboard & mice input

---

include/ace/managers/memory.h
src/ace/managers/memory.c

Eases out-of-bounds debugging in heap-allocated regions.
Right trashing occurs mostly when array indices become bigger than array size. Left trashes are more tricky to interpret, but are indicating that something's wrong is going on in memory.

Added memory trash detection

---

tools/src/common/bitmap.cpp

If palette size is 256 the uint_t counter on tPlanarBitmap constructor is not enough and we end up on a endless loop because the comparison will always be performed with something less of 256 (unsigned int g
I changed added 8 more bits to the i counter and casted Palette.m_vColors.size for clarity, in this way 16 bits will be involved on the comparison and they are enough for 256 colors.

Fix comparison issue con tPlanarBitmap constructor

---

tools/src/common/palette.cpp

Today I had an issue with palette_conv,
if the input file does not end with an empty line, palette_conv is stuck in an endless loop.
My take on this is if the end of file is reached, the szLine is not cleared by std:getline and the exit condition is never met ( szLine == "")
My input file was not generated with gimp, it was a simple copy and paste from another text file, but It had the same structure of yours except for the last line.
Please review my additions, tell me what you think about this issue and eventually merge it into master.

fix palette conv endless loop if source file does not end with a newline

---

include/ace/utils/bitmap.h
include/ace/utils/palette.h
src/ace/utils/bitmap.c
src/ace/utils/palette.c

As the commit message states I implemented bitmapLoadFromMem and paletteLoadFromMem.
This functions should perform the same exact tasks of their LoadFromFile counterparts.
Sometimes I like to store raw data (images and palettes in this case) on variables rather than relying on .plt and .bm files on filesystem loaded at runtime because in the future I am planning to store the whole game on a NDOS disk where I don't have a filesystem, so this features could be handy.

new functions bitmapLoadFromMem and paletteLoadFromMem implemented

---

src/ace/managers/system.c

With this commit interrupts are working on  68010+ systems which don't have VBR at zero.
Code was taken from issue #78 and tested on vampire v600 + coffin r52.
This commit closes #78 hopefully.

Vector base register fixed for 68010+ systems

---

include/ace/utils/font.h
src/ace/utils/font.c

In this PL I fixed a problem about the length of font data loaded into memory, furthermore I added a loadfrommem variant of FontCreate in case the user doesnt want to load the font data from file.
Hope I respected all your coding standard if not let me know.

Better font loading

---

tools/src/common/bitmap.cpp

As I tried to build germz from scratch, this line was causing problems. When `lodepng_decode24_file` fails, nothing is allocated under `pData`, so freeing memory cause crashes.

Fixed tChunkyBitmap::fromPng error handling

---

CMakeLists.txt

More reliable way to handle `#` in mask color from my end.

Escaping mask color value in CMake

---

include/ace/generic/main.h

I noticed this hangs on Linux when the logfile is opened for writing if the calls are in the previous order.

Fix logfile writing

---

src/ace/managers/system.c

Fixed INTF_SETCLR (even if same value as DMAF_SETCLR), to make code more accurate
This bug was messing up sprites when ptplayer is set to use PTPLAYER_USE_VBL: since INTB_VERTB is equal to DMAB_SPRITE.

Fixed clearing interupt instead of dmacon when disabling handler

---

src/ace/managers/ptplayer.c

Fixed timer A interrupt cleanup code when using VBL
and slight performance boost when loading MOD (especially from floppy) by not query getFileSize() twice

Small Ptplayer optim and fix

---

include/ace/generic/screen.h
src/ace/managers/viewport/scrollbuffer.c
src/ace/managers/viewport/simplebuffer.c

On AGA depth modes, the copper needs a little bit more time to do it's magic, so the Constant value is now a small lookup table.
These values can probably be tweaked a little to make it a bit tighter but it fixes the corruption that I was getting with My AGA Branch of ACE.

Fix for AGA depth modes, and how long the Copper needs to wait before it does it's magic.

---

include/ace/generic/screen.h

You know, sometimes I forget how to count.
Added an extra element to account for that rare 0 bitplanes..
An alternate solution is to subtract 1 from the bpp when doing the lookup but that would mean it is a little less optimized.

Copper x wait fix

---

CMakeLists.txt

Enhances convertBitmaps CMake macro by allowing to skip bitmaps generation. Useful if one needs only mask output from source png.

added option to output only masks during bitmap conversion

---

include/ace/managers/bob.h
include/ace/managers/viewport/tilebuffer.h
src/ace/managers/bob.c

Adds `bobSetWidth()` and `bobSetHeight()` functions, allowing resizing them inside game's loop.

Added Bob resize functions

---

tools/src/common/glyph_set.cpp
tools/src/common/glyph_set.h

Fixes the algorithm for trimming empty space around ttf font glyphs.
Closes #201
Closes #202

font_conv: fix trimming ttf fonts

---

docs/programming/hello_world.md
include/ace/managers/state.h
showcase/src/game.c
src/ace/managers/state.c

Makes the stateCreate() function use more straightforward and less error-prone.
The pPrev field has strictly internal functionality and shouldn't be exposed to (first-time) user.
Manually tampering with it, if ever useful, is considered an advanced use, requiring good knowledge of state manager's internals.

remove stateCreate()'s pPrev param

---

docs/installing/tools.md

Out of the box you can't build tools on a Mac. These instructions are a bit transient on purpose since lots of people use a Mac to compile for native Mac/iOS which assumes Clang. If not, you might want to set your system up to always use GCC (or use something like `CMAKE_USER_MAKE_RULES_OVERRIDE` 🤔).
[ ] My code follows the code style of this project.
[x] My change requires a change to the documentation.
[x] I have updated the documentation accordingly.

Update tools.md instructions for MacOS

---

include/ace/managers/memory.h
src/ace/managers/memory.c

Extract logging of peak CHIP/RAM usage into callable function in memory.c/h for debugging purposes.

Extract memLogPeak() into function

---

showcase/CMakeLists.txt
showcase/src/test/interleaved.c
showcase/src/test/twister.c
src/ace/managers/blit.c
src/ace/utils/bitmap.c

Makes the blitCopy() significantly faster when using on interleaved bitmaps.
The showcase twister is faster now.
Also fixes modulo calculations for blitCopyAligned() when using mixed interleaved/non-interleaved bitmaps.

Add support for interleaved blitcopy

---

include/ace/generic/main.h

Adds ability to disable timer manager in generic main code.
I've left it on by default, because currently log blocks depend on it to display time measurements (like they were correct anyway lol). Also, this approach won't break already made games.

generic main: add ability to disable timer manager

---

CMakeLists.txt
tools/src/bitmap_conv.cpp
tools/src/common/palette.cpp
tools/src/common/palette.h
tools/src/common/parse.h
tools/src/common/rgb.cpp
tools/src/common/rgb.h

Adds support for EHB-enabled image conversion.
The new switch simply expands loaded palette with EHB color counterparts so that user doesn't have to pass in 64-color palette created only for purpose of bitmap conversion.
Also, minor cleanup in tool's code reduces amount of warnings under MSVC.

bitmap_conv: add support for EHB palettes

---

include/ace/generic/screen.h
include/ace/managers/bob.h
include/ace/utils/extview.h
src/ace/managers/copper.c
src/ace/managers/sprite.c
src/ace/managers/viewport/scrollbuffer.c
src/ace/managers/viewport/simplebuffer.c
src/ace/utils/extview.c

Adds support for setting view widths different than 320px as well as adding an X margin. Sample creation of 256x224 view:
```c
s_pView = viewCreate(0,
TAG_VIEW_WINDOW_HEIGHT, 224,
TAG_VIEW_WINDOW_WIDTH, 256,
TAG_VIEW_WINDOW_START_X, SCREEN_XOFFSET + (SCREEN_PAL_WIDTH - 256) / 2,
TAG_END);
```

Add support for narrow view sizes and x offsets

---

CMakeLists.txt
include/ace/managers/viewport/tilebuffer.h
src/ace/managers/viewport/tilebuffer.c
src/ace/utils/extview.c
tools/CMakeLists.txt

Allows having a tilemap larger than 256 tiles. Can be configured in CMakeLists.txt by setting following before adding ACE's subdirectory:
```cmake
set(ACE_TILEBUFFER_TILE_TYPE UWORD) # Or any other type
```
Defaults to `UBYTE`.

Generalize tilebuffer's tile index type

---

docs/programming/sprites.md

Smallest PR of the world
Small typo in sprite code, was missing a star *

fix: typo in sprite tutorial

---

src/ace/managers/sprite.c

There's a cop block waiting for 0,0 to reset all sprite pointers to 0x0, so to ensure proper sorting, the cop blocks to set sprite pointers for enabled sprites should wait for a line later.

Fix wait position for setting sprite pointers in cop block mode

---

docs/programming/sprites.md
include/ace/managers/sprite.h
include/ace/utils/sprite.h
src/ace/managers/sprite.c
src/ace/utils/sprite.c

This is not nice, but I wanted to start discussing how to get around the problem that I get into conflicts with the sprite manager if I do my own sprite system:
```
[build] D:/greatflight/src/sprites.c:126:19: error: 's_spriteData' causes a section type conflict with 's_uBlankSprite'
[build]   126 | static UWORD CHIP s_spriteData[] = {
[build]       |                   ^
[build] D:/greatflight/deps/ACE/src/ace/managers/sprite.c:29:41: note: 's_uBlankSprite' was declared here
[build]    29 | static const tHardwareSpriteHeader CHIP s_uBlankSprite;
[build]       |                                         ^
[build] lto-wrapper.exe: fatal error: c:\Users\timfe\.vscode\extensions\bartmanabyss.amiga-debug-1.7.7\bin\win32\opt\bin\m68k-amiga-elf-gcc.exe returned 1 exit status
```
This hack works …

Change sprite manager to allow user to pass their own blank sprite.

---

cmake/ace_functions.cmake
include/ace/managers/memory.h
include/ace/managers/ptplayer.h
include/ace/managers/system.h
include/ace/utils/disk_file.h
include/ace/utils/disk_file_private.h
include/ace/utils/file.h
include/ace/utils/pak_file.h
src/ace/managers/log.c
src/ace/managers/memory.c
src/ace/managers/ptplayer.c
src/ace/managers/system.c
src/ace/utils/bitmap.c
src/ace/utils/disk_file.c
src/ace/utils/file.c
src/ace/utils/font.c
src/ace/utils/pak_file.c
src/ace/utils/palette.c
tools/src/audio_conv.cpp
tools/src/common/compress.cpp
tools/src/common/compress.hpp
tools/src/common/sfx.cpp
tools/src/common/sfx.h
tools/src/mod_tool.cpp
tools/src/pak_tool.cpp

Adds support for custom lossless DPCM compression in audio files, as well as ability to compress entire pakfile with LZ77-like algorithm. Also adds diskFile caching, making reads/writes significantly faster. The compression is optional and when turned on, predictably slow things down a bit.
Also added some minor but breaking changes, like replacing diskFileOpen's std-like file access mode string param in favor of an enum, so that runtime cache checks for given mode can be done more efficiently and using unsupported modes like "x" won't be allowed.
Also adds `systemIsStartVolumeWritable()` which allows checking if the disk is write-protected. ACE now also prevents opening system requesters on file open failure, preventing game freezes in the process.
Also ptplayer sample-packs have now …

Add support for compression

---

docs/tools/palette_conv.md
tools/src/palette_conv.cpp

Rename -nocs option to -cc (convert colors)
Addresses feedback left in #258

Rename paletteConv -nocs option to -cc
