- .gitattributes
Obj-c is evil, c++ is overhead.
Stats are crusial, let's make them accurate!
> Fixed .gitattributes for linguist language detection

- include/ace/utils/chunky.h
- src/ace/utils/chunky.c
Implements part of functionality discussed in #27
> Made chunkyRotate() use passed sin/cos values

- include/ace/macros.h
- include/ace/managers/blit.h
- showcase/src/menu/menu.c
- showcase/src/test/blit.c
- showcase/src/test/copper.c
- showcase/src/test/font.c
- showcase/src/test/lines.c
- showcase/src/test/lines.h
- src/ace/managers/blit.c
Related to #41 and #40. Not sure if those rotate fns will get optimized away in Bebbo's GCC but if not, I'll start an issue there. ;)
> Blit lines and rotate fns

- include/ace/managers/timer.h
- src/ace/managers/system.c
- src/ace/managers/timer.c
- src/ace/utils/extview.c
fixes #70 
Be sure to merge #68  first!
> User vblank handler

- include/ace/managers/memory.h
- include/ace/utils/bitmap.h
- include/ace/utils/chunky.h
- src/ace/managers/blit.c
- src/ace/managers/memory.c
- src/ace/managers/viewport/tilebuffer.c
- src/ace/utils/bitmap.c
- src/ace/utils/chunky.c
This allows having some gfx data loaded to FAST and then memcpy'd into CHIP when needed.
> Bitmap fastmem

- include/ace/managers/audio.h
- src/ace/managers/audio.c
- src/ace/managers/system.c
> Audio initial

- include/fixmath/fix16.h
Added 2 new inline functions for degrees 2 radians and radians 2 degrees conversion.
They work with fix16_t types.
> New inline functions for radians<-->degrees conv

- include/ace/utils/palette.h
- src/ace/utils/palette.c
Dimming a single color can be very useful, in my case more than paletteDim.
> added paletteColorDim function

- src/ace/utils/palette.c
PaletteColorDim call was wrong, indentation was not the same of the other functions in the same file, tried to fix it.
> Indentation issue in latest commits + wrong call

- docs/README.md
- docs/programming/os.md
- include/ace/generic/main.h
- include/ace/managers/system.h
- src/ace/managers/system.c
I've documented some stuff in ACE based on frequent questions I get.
> Generic main documentation

- tools/src/tileset_conv.cpp
Just for my convenience, since the tilesets I'm using come in a 2d grid.
> Support input tilesets being in a 2d grid

- include/ace/managers/viewport/scrollbuffer.h
- include/ace/managers/viewport/tilebuffer.h
- include/ace/utils/custom.h
- src/ace/managers/viewport/scrollbuffer.c
- src/ace/managers/viewport/tilebuffer.c
- src/ace/utils/custom.c
It's not finished, at the very least it's missing a showcase that uses it. But I wanted to open it to get feedback already.
> RAW coplist support in scrollbuffer and tilebuffer

- tools/fmt/include/fmt/core.h
- tools/fmt/include/fmt/format.h
- tools/src/common/math.h
Just some minor things to make it compile again with msvc 19
> Compile tools again with VS2019

- showcase/src/menu/menulist.c
- showcase/src/test/font.c
> font buffer now complies with the divide by 16 rule

- src/ace/managers/ptplayer.c
A pull request for a variety of fixes to ptplayer:
I tried several MODs and now they all sound fantastic. They are probably still some little bugs on some effects, and I have a least two questions for you (KaiN) for further discussion / investigation for later.
> Ptplayer bugfixes

- docs/programming/blit.md
- docs/programming/view.md
Fixed 2 mistakes in docs files
> docs typos

- src/ace/managers/system.c
> ensure that VBR query code plays nice with cpu caches

- src/ace/managers/log.c
- src/ace/managers/system.c
- src/ace/utils/file.c
> Fix file logs

- CMakeLists.txt
- docs/installing/ace.md
- docs/programming/hello_world.md
> Better standalone build

- docs/contributing/codestyle.md
- include/ace/generic/main.h
- include/ace/managers/audio.h
- include/ace/managers/blit.h
- include/ace/managers/copper.h
- include/ace/managers/sprite.h
- include/ace/utils/sprite.h
- src/ace/managers/blit.c
- src/ace/managers/ptplayer.c
fixes #125 
also improves documentation a bit
> Fix release warnings

- docs/contributing/codestyle.md
- include/ace/generic/main.h
- include/ace/macros.h
- include/ace/types.h
- include/ace/utils/file.h
- include/ace/utils/palette.h
- include/mini_std/stdio.h
- src/ace/managers/blit.c
- src/ace/managers/system.c
- src/ace/managers/timer.c
- src/ace/utils/extview.c
- src/ace/utils/file.c
- src/ace/utils/palette.c
- src/mini_std/stdio_file.c
- src/mini_std/stdlib.c
Miscellaneous fixes from ptplayer branch which aren't related to ptplayer. Moved to separate branch to make PRs smaller and more digestible.
> Misc stuff from ptplayer-update branch

- src/ace/managers/system.c
> Enable/disable cdtv device if present on system use/unuse

- include/ace/generic/screen.h
This encodes the experience of @timfel and @Vairn until we add proper calculation.
> Update wait positions for EHB and AGA from experience.

- cmake/ace_functions.cmake
- docs/tools/palette_conv.md
Add CONVERT_COLORS to convertPalette CMake function. Also update docs.
I don't have much CMake experience so it was mostly copied and pasted from how convertBitmaps does it.
> Add CONVERT_COLORS to convertPalette CMake function

- docs/README.md
- docs/programming/fixed_point.md
Adds basic documentation for using fixmath.h
Closes #92 and describes how to achieve desired result from #28.
> Add docs for using fixed point math
